server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: happyday
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    password:
#    timeout: 5000
#jwt配置
jwt:
  expire_time: 3600000
  secret: e3aed01308280829b7c321cc4fbafce4
  auth_path: /user/login
  auth_header: Authorization
debug: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.husky: DEBUG